// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKvMxkPXNcLHN8VRk5uz8VXUJKWSjuc6s',
    appId: '1:131893690805:web:61a4f08c787e8fb7aa99fc',
    messagingSenderId: '131893690805',
    projectId: 'flutter-chat-app-a88f8',
    authDomain: 'flutter-chat-app-a88f8.firebaseapp.com',
    storageBucket: 'flutter-chat-app-a88f8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwSMzTvN1RU-BiR299YjbKLi3DCHvAO5M',
    appId: '1:131893690805:android:08b97af85a428be3aa99fc',
    messagingSenderId: '131893690805',
    projectId: 'flutter-chat-app-a88f8',
    storageBucket: 'flutter-chat-app-a88f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx74b7c80DlBCAa5zJA3a1wKux4j3vC_A',
    appId: '1:131893690805:ios:3f050eb70efcc816aa99fc',
    messagingSenderId: '131893690805',
    projectId: 'flutter-chat-app-a88f8',
    storageBucket: 'flutter-chat-app-a88f8.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx74b7c80DlBCAa5zJA3a1wKux4j3vC_A',
    appId: '1:131893690805:ios:9a91f3dd938ea99baa99fc',
    messagingSenderId: '131893690805',
    projectId: 'flutter-chat-app-a88f8',
    storageBucket: 'flutter-chat-app-a88f8.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
